import Vue from 'vue';
import Header from './components/Header.vue';
import Input from './components/Input.vue';
import SlideBar from './components/SlideBar.vue';
import Menu from './components/Menu.vue';
import NavItem from './components/NavItem.vue';
import Button from './components/Button.vue';
import MarkDown from './components/MarkDown.vue';
import Table from './components/Table.vue';
import select from './components/Select.vue';
import option from './components/Option.vue';
import ModelCase from './components/ModelCase.vue';
import Editor from './components/Editor.vue';
import UserBox from './components/UserBox.vue';
Vue.component('ng-el-UserBox',UserBox);
Vue.component('ng-el-Editor',Editor);
Vue.component('ng-el-modelCase',ModelCase);
Vue.component('ng-el-option',option);
Vue.component('ng-el-select',select);
Vue.component('el-table',Table);
Vue.component('el-MarkDown',MarkDown);
Vue.component('el-Button',Button);
Vue.component('el-nav-item',NavItem);
Vue.component('el-Menu',Menu);
Vue.component('SlideBar',SlideBar);
Vue.component('Input',Input);
Vue.component('Header',Header);